# Generated by Django 5.0 on 2023-12-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_app", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="image",
            field=models.ImageField(default="1", upload_to="images/"),
            preserve_default=False,
        ),
    ]
