# Generated by Django 5.0 on 2023-12-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_app", "0003_song_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="audio_path",
            field=models.FileField(upload_to="media/song/"),
        ),
        migrations.AlterField(
            model_name="song",
            name="image",
            field=models.ImageField(upload_to="media/images/"),
        ),
    ]
