# Generated by Django 5.0 on 2023-12-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_app", "0005_remove_playlist_title_alter_song_audio_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="name",
            field=models.CharField(default="1", max_length=100),
            preserve_default=False,
        ),
    ]
