# Generated by Django 4.2.1 on 2023-12-25 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("music_app", "0006_playlist_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlist",
            name="name",
        ),
    ]
