# Generated by Django 4.2.1 on 2023-12-25 03:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("music_app", "0007_remove_playlist_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
